In [10]:
import pandas as pd
data = pd.read_csv('data.csv')
import numpy as np
np.random.seed(55)

X = np.array(data[['x1','x2']])
y = np.array(data['y'])
y

array([-1.,  1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1.,  1., -1.,
        1., -1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1., -1., -1., -1.,
       -1., -1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1., -1.,
       -1.,  1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,
        1., -1., -1., -1.,  1., -1., -1.,  1.,  1.,  1., -1., -1.,  1.,
       -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1., -1., -1.,  1., -1.,
       -1., -1.,  1.,  1., -1., -1.,  1.,  1.,  1.])

In [24]:
permu = np.random.permutation(100)
permu

array([60, 66, 53, 29, 35, 44, 47, 28, 65, 64, 75, 30, 20, 61, 11, 74, 12,
       97, 26, 63, 81, 68, 38,  6, 99, 34, 25, 57,  3, 56,  0, 78, 45, 17,
       96, 85, 58, 21,  9, 95, 69, 77, 43, 94, 37, 19, 98, 10, 51, 86,  2,
       24, 32, 91, 59, 50, 72, 39, 76,  8, 15, 92, 48, 40, 88, 80,  1, 42,
       73, 36, 49, 93, 54, 62, 67, 71, 16, 83, 31, 13,  7, 84, 52, 82, 87,
       18, 22, 55,  5, 33, 27, 14,  4, 79, 46, 89, 41, 23, 90, 70])

In [46]:
a = np.arange(100)
b = a[permu]
b

array([60, 66, 53, 29, 35, 44, 47, 28, 65, 64, 75, 30, 20, 61, 11, 74, 12,
       97, 26, 63, 81, 68, 38,  6, 99, 34, 25, 57,  3, 56,  0, 78, 45, 17,
       96, 85, 58, 21,  9, 95, 69, 77, 43, 94, 37, 19, 98, 10, 51, 86,  2,
       24, 32, 91, 59, 50, 72, 39, 76,  8, 15, 92, 48, 40, 88, 80,  1, 42,
       73, 36, 49, 93, 54, 62, 67, 71, 16, 83, 31, 13,  7, 84, 52, 82, 87,
       18, 22, 55,  5, 33, 27, 14,  4, 79, 46, 89, 41, 23, 90, 70])