In [1]:
import numpy as np
import torch

x = torch.rand(3,2)
x

tensor([[0.9832, 0.9564],
        [0.4163, 0.5683],
        [0.5836, 0.1666]])

In [2]:
x.size()

torch.Size([3, 2])

In [3]:
y = torch.ones(x.size())
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [5]:
z = x +y 
z

tensor([[1.9832, 1.9564],
        [1.4163, 1.5683],
        [1.5836, 1.1666]])

In [7]:
z[:, 1:]

tensor([[1.9564],
        [1.5683],
        [1.1666]])

In [8]:
z.add(1)

tensor([[2.9832, 2.9564],
        [2.4163, 2.5683],
        [2.5836, 2.1666]])

In [9]:
z

tensor([[1.9832, 1.9564],
        [1.4163, 1.5683],
        [1.5836, 1.1666]])

In [10]:
z.add_(1)

tensor([[2.9832, 2.9564],
        [2.4163, 2.5683],
        [2.5836, 2.1666]])

In [11]:
z

tensor([[2.9832, 2.9564],
        [2.4163, 2.5683],
        [2.5836, 2.1666]])

In [12]:
z.size()

torch.Size([3, 2])

In [13]:
z.resize_(2,3)

tensor([[2.9832, 2.9564, 2.4163],
        [2.5683, 2.5836, 2.1666]])

In [14]:
z

tensor([[2.9832, 2.9564, 2.4163],
        [2.5683, 2.5836, 2.1666]])

In [15]:
a = np.random.rand(4,3)
a

array([[0.78380822, 0.28414481, 0.86921596],
       [0.24085181, 0.83426158, 0.60770048],
       [0.25394419, 0.46674268, 0.32917291],
       [0.60384814, 0.37408609, 0.77753717]])

In [17]:
b = torch.from_numpy(a)
b

tensor([[0.7838, 0.2841, 0.8692],
        [0.2409, 0.8343, 0.6077],
        [0.2539, 0.4667, 0.3292],
        [0.6038, 0.3741, 0.7775]], dtype=torch.float64)

In [18]:
b.numpy()

array([[0.78380822, 0.28414481, 0.86921596],
       [0.24085181, 0.83426158, 0.60770048],
       [0.25394419, 0.46674268, 0.32917291],
       [0.60384814, 0.37408609, 0.77753717]])

In [21]:
b.mul(2)

tensor([[3.1352, 1.1366, 3.4769],
        [0.9634, 3.3370, 2.4308],
        [1.0158, 1.8670, 1.3167],
        [2.4154, 1.4963, 3.1101]], dtype=torch.float64)

In [22]:
a

array([[1.56761645, 0.56828962, 1.73843192],
       [0.48170362, 1.66852317, 1.21540097],
       [0.50788838, 0.93348536, 0.65834582],
       [1.20769627, 0.74817219, 1.55507433]])